# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from myLabel import myLabel
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnSheppCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnSheppCreate.setCheckable(False)
        self.btnSheppCreate.setFlat(True)
        self.btnSheppCreate.setObjectName("btnSheppCreate")
        self.horizontalLayout_13.addWidget(self.btnSheppCreate)
        self.comboSheppSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboSheppSize.setObjectName("comboSheppSize")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.horizontalLayout_13.addWidget(self.comboSheppSize)
        self.horizontalLayout.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowse.sizePolicy().hasHeightForWidth())
        self.btnBrowse.setSizePolicy(sizePolicy)
        self.btnBrowse.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.phantomlbl = myLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantomlbl.sizePolicy().hasHeightForWidth())
        self.phantomlbl.setSizePolicy(sizePolicy)
        self.phantomlbl.setMouseTracking(True)
        self.phantomlbl.setFrameShape(QtWidgets.QFrame.Box)
        self.phantomlbl.setText("")
        self.phantomlbl.setObjectName("phantomlbl")
        self.horizontalLayout_14.addWidget(self.phantomlbl)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGraph = QtWidgets.QWidget()
        self.tabGraph.setObjectName("tabGraph")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabGraph)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsPlotT1 = PlotWidget(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT1.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT1.setSizePolicy(sizePolicy)
        self.graphicsPlotT1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT1.setObjectName("graphicsPlotT1")
        self.verticalLayout_6.addWidget(self.graphicsPlotT1)
        self.graphicsPlotT2 = PlotWidget(self.tabGraph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT2.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT2.setSizePolicy(sizePolicy)
        self.graphicsPlotT2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT2.setObjectName("graphicsPlotT2")
        self.verticalLayout_6.addWidget(self.graphicsPlotT2)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tabGraph, "")
        self.tabKspace = QtWidgets.QWidget()
        self.tabKspace.setObjectName("tabKspace")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabKspace)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kspaceLbl = QtWidgets.QLabel(self.tabKspace)
        self.kspaceLbl.setMinimumSize(QtCore.QSize(128, 128))
        self.kspaceLbl.setMouseTracking(True)
        self.kspaceLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.kspaceLbl.setText("")
        self.kspaceLbl.setObjectName("kspaceLbl")
        self.verticalLayout.addWidget(self.kspaceLbl)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabKspace, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.prepSelc = QtWidgets.QComboBox(self.groupBox)
        self.prepSelc.setObjectName("prepSelc")
        self.prepSelc.addItem("")
        self.prepSelc.addItem("")
        self.prepSelc.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.prepSelc)
        self.Invtime = QtWidgets.QLineEdit(self.groupBox)
        self.Invtime.setObjectName("Invtime")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Invtime)
        self.acqBox = QtWidgets.QComboBox(self.groupBox)
        self.acqBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.acqBox.setObjectName("acqBox")
        self.acqBox.addItem("")
        self.acqBox.addItem("")
        self.acqBox.addItem("")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.acqBox)
        self.InvTimeText = QtWidgets.QLabel(self.groupBox)
        self.InvTimeText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.InvTimeText.setObjectName("InvTimeText")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.InvTimeText)
        self.T2prepText = QtWidgets.QLabel(self.groupBox)
        self.T2prepText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.T2prepText.setObjectName("T2prepText")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.T2prepText)
        self.T2prep = QtWidgets.QLineEdit(self.groupBox)
        self.T2prep.setMaximumSize(QtCore.QSize(150, 200))
        self.T2prep.setObjectName("T2prep")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.T2prep)
        self.spacingText = QtWidgets.QLabel(self.groupBox)
        self.spacingText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spacingText.setObjectName("spacingText")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.spacingText)
        self.spacingSW = QtWidgets.QLineEdit(self.groupBox)
        self.spacingSW.setObjectName("spacingSW")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.spacingSW)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsRep = PlotWidget(self.tab)
        self.graphicsRep.setObjectName("graphicsRep")
        self.gridLayout_3.addWidget(self.graphicsRep, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_14.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.showGraphics = QtWidgets.QPushButton(self.centralwidget)
        self.showGraphics.setObjectName("showGraphics")
        self.verticalLayout_2.addWidget(self.showGraphics)
        self.startSeq = QtWidgets.QPushButton(self.centralwidget)
        self.startSeq.setObjectName("startSeq")
        self.verticalLayout_2.addWidget(self.startSeq)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12, 0, QtCore.Qt.AlignRight)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.comboViewMode = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboViewMode.sizePolicy().hasHeightForWidth())
        self.comboViewMode.setSizePolicy(sizePolicy)
        self.comboViewMode.setObjectName("comboViewMode")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.horizontalLayout_15.addWidget(self.comboViewMode)
        spacerItem4 = QtWidgets.QSpacerItem(90, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.startCyc = QtWidgets.QLineEdit(self.centralwidget)
        self.startCyc.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startCyc.setObjectName("startCyc")
        self.horizontalLayout_15.addWidget(self.startCyc)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13, 0, QtCore.Qt.AlignRight)
        self.TimeEcho = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeEcho.setMaximumSize(QtCore.QSize(50, 20))
        self.TimeEcho.setObjectName("TimeEcho")
        self.horizontalLayout_15.addWidget(self.TimeEcho)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14, 0, QtCore.Qt.AlignRight)
        self.TimeRepeat = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeRepeat.setMaximumSize(QtCore.QSize(40, 20))
        self.TimeRepeat.setObjectName("TimeRepeat")
        self.horizontalLayout_15.addWidget(self.TimeRepeat)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15, 0, QtCore.Qt.AlignRight)
        self.FlipAngle = QtWidgets.QLineEdit(self.centralwidget)
        self.FlipAngle.setMaximumSize(QtCore.QSize(40, 20))
        self.FlipAngle.setObjectName("FlipAngle")
        self.horizontalLayout_15.addWidget(self.FlipAngle)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI Sequence Simulator"))
        self.btnSheppCreate.setText(_translate("MainWindow", "Shepp-Logan"))
        self.comboSheppSize.setItemText(0, _translate("MainWindow", "32"))
        self.comboSheppSize.setItemText(1, _translate("MainWindow", "64"))
        self.comboSheppSize.setItemText(2, _translate("MainWindow", "128"))
        self.comboSheppSize.setItemText(3, _translate("MainWindow", "256"))
        self.comboSheppSize.setItemText(4, _translate("MainWindow", "512"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraph), _translate("MainWindow", "Graphs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKspace), _translate("MainWindow", "K-space "))
        self.groupBox.setTitle(_translate("MainWindow", "Preparation and Acquisition"))
        self.prepSelc.setItemText(0, _translate("MainWindow", "Inversion"))
        self.prepSelc.setItemText(1, _translate("MainWindow", "T2prep"))
        self.prepSelc.setItemText(2, _translate("MainWindow", "Tagging"))
        self.Invtime.setText(_translate("MainWindow", "4.3"))
        self.acqBox.setItemText(0, _translate("MainWindow", "GRE"))
        self.acqBox.setItemText(1, _translate("MainWindow", "SSFP"))
        self.acqBox.setItemText(2, _translate("MainWindow", "SE"))
        self.InvTimeText.setText(_translate("MainWindow", "Inversion Time"))
        self.T2prepText.setText(_translate("MainWindow", "T2 time"))
        self.T2prep.setText(_translate("MainWindow", "2"))
        self.spacingText.setText(_translate("MainWindow", "Spacing of sin wave"))
        self.spacingSW.setText(_translate("MainWindow", "7"))
        self.label_2.setText(_translate("MainWindow", "Preparation"))
        self.label_3.setText(_translate("MainWindow", "Acquisition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Pulse Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Graphical Representation"))
        self.showGraphics.setText(_translate("MainWindow", "Show Graphical Representation"))
        self.startSeq.setText(_translate("MainWindow", "Start Sequence"))
        self.label_12.setText(_translate("MainWindow", "Show"))
        self.comboViewMode.setItemText(0, _translate("MainWindow", "PD"))
        self.comboViewMode.setItemText(1, _translate("MainWindow", "T1"))
        self.comboViewMode.setItemText(2, _translate("MainWindow", "T2"))
        self.label.setText(_translate("MainWindow", "Start up cycles"))
        self.startCyc.setText(_translate("MainWindow", "10"))
        self.label_13.setText(_translate("MainWindow", "TE"))
        self.TimeEcho.setText(_translate("MainWindow", "0.001"))
        self.label_14.setText(_translate("MainWindow", "TR"))
        self.TimeRepeat.setText(_translate("MainWindow", "0.5"))
        self.label_15.setText(_translate("MainWindow", "FA"))
        self.FlipAngle.setText(_translate("MainWindow", "90"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

